[cmake]
minimum_required = "3.0"

[project]
name = "cmkr"
version = "0.1.0"

[[bin]]
name = "cmkrlib"
type = "static"
sources = ["src/args.cpp", "src/gen.cpp", "src/help.cpp"]
include_dirs = ["vendor"]
features = ["cxx_std_17"]

[[bin]]
name = "cmkr"
type = "exe"
sources = ["src/main.cpp"]
link_libs = ["cmkrlib"]

