[cmake]
minimum = "3.15"

[project]
name = "cmkr"
version = "0.1.3"
inject-after = "add_subdirectory(third_party)"

[[target]]
name = "cmkrlib"
type = "static"
sources = ["src/cmkrlib/*.cpp", "src/cmkrlib/*.hpp", "include/*.h"]
include-directories = ["include"]
compile-features = ["cxx_std_11"]
link-libraries = ["toml11", "ghc_filesystem", "mpark_variant"]

[[target]]
name = "cmkr"
type = "executable"
sources = ["src/main.cpp"]
link-libraries = ["cmkrlib"]

[[install]]
targets = ["cmkr"]
destination = "${CMAKE_INSTALL_PREFIX}/bin"
