[cmake] # required
minimum_required = "3.0" # required
# cpp_flags = [] # optional
# c_flags = [] # optional
# linker_flags = [] # optional
# subdirs = [] # optional

[project] # required
name = "cmkr" # required
version = "0.1.0" # required

# [dependencies] # optional, runs find_package, use "*" to ignore version
# boost = "1.74.0"

[[bin]] # required
name = "cmkr" # required
type = "exe" # required (exe || shared || static)
sources = ["src/main.cpp", "src/args.cpp", "src/gen.cpp"] # required
include_directories = ["vendor"] # optional
compile_features = ["cxx_std_17"] # optional
# definitions = [] # optional
# link_libraries = [] # optional 

