title: cmkr

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Automatically deduce dark theme preference https://github.com/pmarsceill/just-the-docs/pull/464
remote_theme: build-cpp/just-the-docs@light-switch
search_enabled: true
color_scheme: light-or-dark
heading_anchors: true
aux_links:
  "GitHub":
    - "https://github.com/build-cpp/cmkr"
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/build-cpp/cmkr"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
gh_edit_source: docs

production_url : https://cmkr.build
footer_content: |
  <script src="https://utteranc.es/client.js"
          repo="build-cpp/cmkr-docs-comments"
          issue-term="pathname"
          theme="preferred-color-scheme"
          crossorigin="anonymous"
          async>
  </script>