title: cmkr

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Automatically deduce dark theme preference https://github.com/pmarsceill/just-the-docs/pull/464
remote_theme: build-cpp/just-the-docs@light-switch
search_enabled: true
color_scheme: light-or-dark
heading_anchors: true
aux_links:
  "GitHub":
    - "https://github.com/build-cpp/cmkr"
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/build-cpp/cmkr"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
gh_edit_source: docs

ga_tracking: G-DY172KY7Z9

production_url : https://cmkr.build
footer_content: |
  <script src="https://giscus.app/client.js"
          data-repo="build-cpp/cmkr"
          data-repo-id="MDEwOlJlcG9zaXRvcnkyOTQwMDc3MzY="
          data-category="Documentation"
          data-category-id="DIC_kwDOEYYzuM4CTXeA"
          data-mapping="pathname"
          data-strict="1"
          data-reactions-enabled="1"
          data-emit-metadata="0"
          data-input-position="top"
          data-theme="preferred_color_scheme"
          data-lang="en"
          crossorigin="anonymous"
          async>
  </script>