# This is a minimal example project used for testing the cmkr bootstrapping process

[cmake]
version = "3.15"

[project]
name = "example"
version = "0.1.0"

[target.example]
type = "executable"
sources = ["src/example.cpp"]