name: CMake

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '${{ github.repository }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-2019, macos-10.15, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install"
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
        cmake --install build --config ${{ env.BUILD_TYPE }}

    - name: Check if cmkr was run
      run: |
        ./install/bin/cmkr gen
        git diff --exit-code

    - name: Test
      run: |
        cd build/tests
        ctest -C ${{ env.BUILD_TYPE }}
