name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-18.04]

    steps:
    - name: configure
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          export CXX=g++-9
         fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Build
      run: cmake -S. -Bbin && cmake --build bin --config $BUILD_TYPE
